#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Nov 02, 2018 08:56:19 PM +0200  platform: Windows NT

import sys
from Data_Shapes import *
path_to_tool = sys.argv[0].split("/")
path_to_tool.pop()
temp = ""
for word in path_to_tool:
    temp += word + "/"
path_to_tool = temp[:-1]
#sys.path.insert(0, path_to_tool + "/" + "Shapes")
from Right_Triangle import *

DATABASE = path_to_tool + "/" + "data.txt"


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Creat_Right_Tri_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Creat_Right_Teiangle (root)
    Creat_Right_Tri_support.init(root, top)
    root.mainloop()

w = None
def create_Creat_Right_Teiangle(root, data_obj, canvas, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel(root)
    top = Creat_Right_Teiangle(data_obj, canvas, w)
    Creat_Right_Tri_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Creat_Right_Teiangle():
    global w
    w.destroy()
    w = None


class Creat_Right_Teiangle:
    def __init__(self, data_obj, canvas, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Courier New} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("310x217+618+177")
        top.title("Creat Right Teiangle")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")


        self.canv = canvas
        self.data = data_obj


        self.menubar = Menu(top,font=font9,bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.side_one = Entry(top)
        self.side_one.place(relx=0.29, rely=0.323,height=20, relwidth=0.206)
        self.side_one.configure(background="white")
        self.side_one.configure(disabledforeground="#a3a3a3")
        self.side_one.configure(font=font10)
        self.side_one.configure(foreground="#000000")
        self.side_one.configure(highlightbackground="#d9d9d9")
        self.side_one.configure(highlightcolor="black")
        self.side_one.configure(insertbackground="black")
        self.side_one.configure(selectbackground="#c4c4c4")
        self.side_one.configure(selectforeground="black")

        self.side_1 = Label(top)
        self.side_1.place(relx=0.032, rely=0.276, height=41, width=62)
        self.side_1.configure(activebackground="#f9f9f9")
        self.side_1.configure(activeforeground="black")
        self.side_1.configure(background="#d9d9d9")
        self.side_1.configure(disabledforeground="#a3a3a3")
        self.side_1.configure(foreground="#000000")
        self.side_1.configure(highlightbackground="#d9d9d9")
        self.side_1.configure(highlightcolor="black")
        self.side_1.configure(text='''Side One -''')
        self.side_1.configure(width=62)

        self.side_2 = Label(top)
        self.side_2.place(relx=0.032, rely=0.461, height=21, width=62)
        self.side_2.configure(activebackground="#f9f9f9")
        self.side_2.configure(activeforeground="black")
        self.side_2.configure(background="#d9d9d9")
        self.side_2.configure(disabledforeground="#a3a3a3")
        self.side_2.configure(foreground="#000000")
        self.side_2.configure(highlightbackground="#d9d9d9")
        self.side_2.configure(highlightcolor="black")
        self.side_2.configure(text='''Side Two -''')

        self.side_two = Entry(top)
        self.side_two.place(relx=0.29, rely=0.461,height=20, relwidth=0.206)
        self.side_two.configure(background="white")
        self.side_two.configure(disabledforeground="#a3a3a3")
        self.side_two.configure(font=font10)
        self.side_two.configure(foreground="#000000")
        self.side_two.configure(highlightbackground="#d9d9d9")
        self.side_two.configure(highlightcolor="black")
        self.side_two.configure(insertbackground="black")
        self.side_two.configure(selectbackground="#c4c4c4")
        self.side_two.configure(selectforeground="black")

        self.x_start = Entry(top)
        self.x_start.place(relx=0.29, rely=0.599,height=20, relwidth=0.206)
        self.x_start.configure(background="white")
        self.x_start.configure(disabledforeground="#a3a3a3")
        self.x_start.configure(font=font10)
        self.x_start.configure(foreground="#000000")
        self.x_start.configure(highlightbackground="#d9d9d9")
        self.x_start.configure(highlightcolor="black")
        self.x_start.configure(insertbackground="black")
        self.x_start.configure(selectbackground="#c4c4c4")
        self.x_start.configure(selectforeground="black")

        self.start_x = Label(top)
        self.start_x.place(relx=0.032, rely=0.599, height=21, width=77)
        self.start_x.configure(activebackground="#f9f9f9")
        self.start_x.configure(activeforeground="black")
        self.start_x.configure(background="#d9d9d9")
        self.start_x.configure(disabledforeground="#a3a3a3")
        self.start_x.configure(foreground="#000000")
        self.start_x.configure(highlightbackground="#d9d9d9")
        self.start_x.configure(highlightcolor="black")
        self.start_x.configure(text='''Start Point (x)''')

        self.txt_creat_right_triangle = Label(top)
        self.txt_creat_right_triangle.place(relx=0.032, rely=0.0, height=41
                , width=134)
        self.txt_creat_right_triangle.configure(activebackground="#f9f9f9")
        self.txt_creat_right_triangle.configure(activeforeground="black")
        self.txt_creat_right_triangle.configure(background="#d9d9d9")
        self.txt_creat_right_triangle.configure(disabledforeground="#a3a3a3")
        self.txt_creat_right_triangle.configure(foreground="#000000")
        self.txt_creat_right_triangle.configure(highlightbackground="#d9d9d9")
        self.txt_creat_right_triangle.configure(highlightcolor="black")
        self.txt_creat_right_triangle.configure(text='''Creat Right Triangle''')

        self.Creat = Button(top)
        self.Creat.place(relx=0.516, rely=0.184, height=164, width=137)
        self.Creat.configure(activebackground="#d9d9d9")
        self.Creat.configure(activeforeground="#000000")
        self.Creat.configure(background="#d9d9d9")
        self.Creat.configure(disabledforeground="#a3a3a3")
        self.Creat.configure(foreground="#000000")
        self.Creat.configure(highlightbackground="#d9d9d9")
        self.Creat.configure(highlightcolor="black")
        self.Creat.configure(pady="0")
        self.Creat.configure(text='''Creat''')
        self.Creat.configure(width=137)
        self.Creat.bind('<Button-1>',lambda e: self.button_pres())

        self.star_y = Label(top)
        self.star_y.place(relx=0.032, rely=0.737, height=21, width=74)
        self.star_y.configure(activebackground="#f9f9f9")
        self.star_y.configure(activeforeground="black")
        self.star_y.configure(background="#d9d9d9")
        self.star_y.configure(disabledforeground="#a3a3a3")
        self.star_y.configure(foreground="#000000")
        self.star_y.configure(highlightbackground="#d9d9d9")
        self.star_y.configure(highlightcolor="black")
        self.star_y.configure(text='''Start Point (y)''')

        self.y_start = Entry(top)
        self.y_start.place(relx=0.29, rely=0.737,height=20, relwidth=0.206)
        self.y_start.configure(background="white")
        self.y_start.configure(disabledforeground="#a3a3a3")
        self.y_start.configure(font=font10)
        self.y_start.configure(foreground="#000000")
        self.y_start.configure(highlightbackground="#d9d9d9")
        self.y_start.configure(highlightcolor="black")
        self.y_start.configure(insertbackground="black")
        self.y_start.configure(selectbackground="#c4c4c4")
        self.y_start.configure(selectforeground="black")

        self.Color = Entry(top)
        self.Color.place(relx=0.29, rely=0.876,height=20, relwidth=0.206)
        self.Color.configure(background="white")
        self.Color.configure(disabledforeground="#a3a3a3")
        self.Color.configure(font=font10)
        self.Color.configure(foreground="#000000")
        self.Color.configure(highlightbackground="#d9d9d9")
        self.Color.configure(highlightcolor="black")
        self.Color.configure(insertbackground="black")
        self.Color.configure(selectbackground="#c4c4c4")
        self.Color.configure(selectforeground="black")

        self.color = Label(top)
        self.color.place(relx=0.032, rely=0.876, height=21, width=61)
        self.color.configure(activebackground="#f9f9f9")
        self.color.configure(activeforeground="black")
        self.color.configure(background="#d9d9d9")
        self.color.configure(disabledforeground="#a3a3a3")
        self.color.configure(foreground="#000000")
        self.color.configure(highlightbackground="#d9d9d9")
        self.color.configure(highlightcolor="black")
        self.color.configure(text='''Color  ----''')

        self.name = Entry(top)
        self.name.place(relx=0.29, rely=0.184,height=20, relwidth=0.206)
        self.name.configure(background="white")
        self.name.configure(disabledforeground="#a3a3a3")
        self.name.configure(font=font10)
        self.name.configure(foreground="#000000")
        self.name.configure(insertbackground="black")
        self.name.configure(width=64)

        self.txt_name = Label(top)
        self.txt_name.place(relx=0.032, rely=0.184, height=21, width=59)
        self.txt_name.configure(background="#d9d9d9")
        self.txt_name.configure(disabledforeground="#a3a3a3")
        self.txt_name.configure(foreground="#000000")
        self.txt_name.configure(text='''Name ---''')
        self.txt_name.configure(width=59)

    def button_pres(self):
        x = self.x_start.get()
        y = self.y_start.get()
        side1 = self.side_one.get()
        side2 = self.side_two.get()
        color = self.Color.get()
        name = self.name.get()
        print self.data.show()
        if x.isdigit() and y.isdigit() and side1.isdigit() and side2.isdigit() and color is not "" and color is not "":
            obj = Right_Tri(int(x), int(y), int(side1), int(side2), color)
            obj_val = obj.draw_me(self.canv)
            print self.canv.coords(obj_val)
            self.data.set_value(name, obj_val)
            value ="Name:  " + name + ":   " + "x: " + x + "   " + "y: " + y + "   " + "side1: " + side1 + "   " + "side2: " + side2 + "   " + "color: " + color + "\n"
            with open(DATABASE, "a") as file:
                file.write(value)
            Creat_Right_Tri_support.destroy_window()






if __name__ == '__main__':
    vp_start_gui()



