#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Oct 29, 2018 11:39:38 AM +0200  platform: Windows NT

import sys
import Creat_Right_Tri

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Main_GUI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    Main_GUI_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Main_GUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("989x724+917+65")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.iso_tri = tk.Button(top)
        self.iso_tri.place(relx=0.0, rely=0.124, height=94, width=127)
        self.iso_tri.configure(activebackground="#d9d9d9")
        self.iso_tri.configure(activeforeground="#000000")
        self.iso_tri.configure(background="#d9d9d9")
        self.iso_tri.configure(disabledforeground="#a3a3a3")
        self.iso_tri.configure(foreground="#000000")
        self.iso_tri.configure(highlightbackground="#d9d9d9")
        self.iso_tri.configure(highlightcolor="black")
        self.iso_tri.configure(pady="0")
        self.iso_tri.configure(text='''Isosceles Triangle''')
        self.iso_tri.bind('<Button-1>',lambda e:Main_GUI_support.xxx(e))

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.0, rely=0.249, height=94, width=127)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Triangle''')

        self.square = tk.Button(top)
        self.square.place(relx=0.0, rely=0.373, height=94, width=127)
        self.square.configure(activebackground="#d9d9d9")
        self.square.configure(activeforeground="#000000")
        self.square.configure(background="#d9d9d9")
        self.square.configure(disabledforeground="#a3a3a3")
        self.square.configure(foreground="#000000")
        self.square.configure(highlightbackground="#d9d9d9")
        self.square.configure(highlightcolor="black")
        self.square.configure(pady="0")
        self.square.configure(text='''Square''')

        self.rectangle = tk.Button(top)
        self.rectangle.place(relx=0.0, rely=0.497, height=94, width=127)
        self.rectangle.configure(activebackground="#d9d9d9")
        self.rectangle.configure(activeforeground="#000000")
        self.rectangle.configure(background="#d9d9d9")
        self.rectangle.configure(disabledforeground="#a3a3a3")
        self.rectangle.configure(foreground="#000000")
        self.rectangle.configure(highlightbackground="#d9d9d9")
        self.rectangle.configure(highlightcolor="black")
        self.rectangle.configure(pady="0")
        self.rectangle.configure(text='''Rectangle''')

        self.parall = tk.Button(top)
        self.parall.place(relx=0.0, rely=0.622, height=94, width=127)
        self.parall.configure(activebackground="#d9d9d9")
        self.parall.configure(activeforeground="#000000")
        self.parall.configure(background="#d9d9d9")
        self.parall.configure(disabledforeground="#a3a3a3")
        self.parall.configure(foreground="#000000")
        self.parall.configure(highlightbackground="#d9d9d9")
        self.parall.configure(highlightcolor="black")
        self.parall.configure(pady="0")
        self.parall.configure(text='''Parallelogram''')

        self.circle = tk.Button(top)
        self.circle.place(relx=0.0, rely=0.746, height=94, width=127)
        self.circle.configure(activebackground="#d9d9d9")
        self.circle.configure(activeforeground="#000000")
        self.circle.configure(background="#d9d9d9")
        self.circle.configure(disabledforeground="#a3a3a3")
        self.circle.configure(foreground="#000000")
        self.circle.configure(highlightbackground="#d9d9d9")
        self.circle.configure(highlightcolor="black")
        self.circle.configure(pady="0")
        self.circle.configure(text='''Circle''')

        self.Button8 = tk.Button(top)
        self.Button8.place(relx=0.0, rely=0.87, height=104, width=127)
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(text='''Ellipse''')

        self.Text1 = tk.Text(top)
        self.Text1.place(relx=0.142, rely=0.0, relheight=0.033, relwidth=0.863)
        self.Text1.configure(background="white")
        self.Text1.configure(font=font9)
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(width=854)
        self.Text1.configure(wrap='word')

        self.Text2 = tk.Text(top)
        self.Text2.place(relx=0.121, rely=0.028, relheight=0.986, relwidth=0.024)

        self.Text2.configure(background="white")
        self.Text2.configure(font=font9)
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="#d9d9d9")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="#c4c4c4")
        self.Text2.configure(selectforeground="black")
        self.Text2.configure(width=24)
        self.Text2.configure(wrap='word')

        self.Text3 = tk.Text(top)
        self.Text3.place(relx=0.121, rely=0.0, relheight=0.033, relwidth=0.024)
        self.Text3.configure(background="white")
        self.Text3.configure(font=font9)
        self.Text3.configure(foreground="black")
        self.Text3.configure(highlightbackground="#d9d9d9")
        self.Text3.configure(highlightcolor="black")
        self.Text3.configure(insertbackground="black")
        self.Text3.configure(selectbackground="#c4c4c4")
        self.Text3.configure(selectforeground="black")
        self.Text3.configure(width=24)
        self.Text3.configure(wrap='word')

        self.menubar = tk.Menu(top,font=font9,bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.142, rely=0.028, relheight=0.985
                , relwidth=0.852)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief='ridge')
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=843)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.0, rely=0.0, height=94, width=127)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Button''')
        self.Button1.configure(width=127)
        self.Button1.bind('<Button-1>',lambda e:Main_GUI_support.Creat_Right_Tri(1,2,3,self))

if __name__ == '__main__':
    vp_start_gui()





