#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Nov 01, 2018 06:15:16 PM +0200  platform: Windows NT

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Main_GUI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    Main_GUI_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    Main_GUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("1002x719+463+138")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")


        self.menubar = Menu(top,font=font9,bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.right_triangle = Button(top)
        self.right_triangle.place(relx=0.0, rely=0.0, height=94, width=127)
        self.right_triangle.configure(activebackground="#d9d9d9")
        self.right_triangle.configure(activeforeground="#000000")
        self.right_triangle.configure(background="#d9d9d9")
        self.right_triangle.configure(disabledforeground="#a3a3a3")
        self.right_triangle.configure(foreground="#000000")
        self.right_triangle.configure(highlightbackground="#d9d9d9")
        self.right_triangle.configure(highlightcolor="black")
        self.right_triangle.configure(pady="0")
        self.right_triangle.configure(text='''Right Triangle''')
        self.right_triangle.bind('<Button-1>',lambda e:Main_GUI_support.creat_right_tri(top, self.shape_c))

        self.isos_triangle = Button(top)
        self.isos_triangle.place(relx=0.0, rely=0.125, height=94, width=127)
        self.isos_triangle.configure(activebackground="#d9d9d9")
        self.isos_triangle.configure(activeforeground="#000000")
        self.isos_triangle.configure(background="#d9d9d9")
        self.isos_triangle.configure(disabledforeground="#a3a3a3")
        self.isos_triangle.configure(foreground="#000000")
        self.isos_triangle.configure(highlightbackground="#d9d9d9")
        self.isos_triangle.configure(highlightcolor="black")
        self.isos_triangle.configure(pady="0")
        self.isos_triangle.configure(text='''Isosceles Triangle''')
        self.isos_triangle.bind('<Button-1>',lambda e:Main_GUI_support.creat_isos_tri(top))

        self.equilateral_triangle = Button(top)
        self.equilateral_triangle.place(relx=0.0, rely=0.25, height=84
                , width=127)
        self.equilateral_triangle.configure(activebackground="#d9d9d9")
        self.equilateral_triangle.configure(activeforeground="#000000")
        self.equilateral_triangle.configure(background="#d9d9d9")
        self.equilateral_triangle.configure(disabledforeground="#a3a3a3")
        self.equilateral_triangle.configure(foreground="#000000")
        self.equilateral_triangle.configure(highlightbackground="#d9d9d9")
        self.equilateral_triangle.configure(highlightcolor="black")
        self.equilateral_triangle.configure(pady="0")
        self.equilateral_triangle.configure(text='''Equilateral Triangle''')
        self.equilateral_triangle.bind('<Button-1>',lambda e:Main_GUI_support.creat_equilateral_triangle(top))

        self.square = Button(top)
        self.square.place(relx=0.0, rely=0.362, height=94, width=127)
        self.square.configure(activebackground="#d9d9d9")
        self.square.configure(activeforeground="#000000")
        self.square.configure(background="#d9d9d9")
        self.square.configure(disabledforeground="#a3a3a3")
        self.square.configure(foreground="#000000")
        self.square.configure(highlightbackground="#d9d9d9")
        self.square.configure(highlightcolor="black")
        self.square.configure(pady="0")
        self.square.configure(text='''Square''')
        self.square.bind('<Button-1>',lambda e:Main_GUI_support.creat_square(top))

        self.rectangle = Button(top)
        self.rectangle.place(relx=0.0, rely=0.487, height=94, width=127)
        self.rectangle.configure(activebackground="#d9d9d9")
        self.rectangle.configure(activeforeground="#000000")
        self.rectangle.configure(background="#d9d9d9")
        self.rectangle.configure(disabledforeground="#a3a3a3")
        self.rectangle.configure(foreground="#000000")
        self.rectangle.configure(highlightbackground="#d9d9d9")
        self.rectangle.configure(highlightcolor="black")
        self.rectangle.configure(pady="0")
        self.rectangle.configure(text='''Rectangle''')
        self.rectangle.bind('<Button-1>',lambda e:Main_GUI_support.creat_rectangle(top))

        self.parallelogram = Button(top)
        self.parallelogram.place(relx=0.0, rely=0.612, height=94, width=127)
        self.parallelogram.configure(activebackground="#d9d9d9")
        self.parallelogram.configure(activeforeground="#000000")
        self.parallelogram.configure(background="#d9d9d9")
        self.parallelogram.configure(disabledforeground="#a3a3a3")
        self.parallelogram.configure(foreground="#000000")
        self.parallelogram.configure(highlightbackground="#d9d9d9")
        self.parallelogram.configure(highlightcolor="black")
        self.parallelogram.configure(pady="0")
        self.parallelogram.configure(text='''Parallelogram''')
        self.parallelogram.bind('<Button-1>',lambda e:Main_GUI_support.creat_parallelogram(top))

        self.circle = Button(top)
        self.circle.place(relx=0.0, rely=0.737, height=94, width=127)
        self.circle.configure(activebackground="#d9d9d9")
        self.circle.configure(activeforeground="#000000")
        self.circle.configure(background="#d9d9d9")
        self.circle.configure(disabledforeground="#a3a3a3")
        self.circle.configure(foreground="#000000")
        self.circle.configure(highlightbackground="#d9d9d9")
        self.circle.configure(highlightcolor="black")
        self.circle.configure(pady="0")
        self.circle.configure(text='''Circle''')
        self.circle.bind('<Button-1>',lambda e:Main_GUI_support.creat_circle(top))

        self.Button10 = Button(top)
        self.Button10.place(relx=0.0, rely=0.862, height=104, width=127)
        self.Button10.configure(activebackground="#d9d9d9")
        self.Button10.configure(activeforeground="#000000")
        self.Button10.configure(background="#d9d9d9")
        self.Button10.configure(disabledforeground="#a3a3a3")
        self.Button10.configure(foreground="#000000")
        self.Button10.configure(highlightbackground="#d9d9d9")
        self.Button10.configure(highlightcolor="black")
        self.Button10.configure(pady="0")
        self.Button10.configure(text='''Ellipse''')
        self.Button10.bind('<Button-1>',lambda e:Main_GUI_support.creat_ellipse(top))

        self.size_c = Canvas(top)
        self.size_c.place(relx=0.12, rely=0.0, relheight=1.006, relwidth=0.881)
        self.size_c.configure(background="#d9d9d9")
        self.size_c.configure(borderwidth="2")
        self.size_c.configure(highlightbackground="#d9d9d9")
        self.size_c.configure(highlightcolor="black")
        self.size_c.configure(insertbackground="black")
        self.size_c.configure(relief=RIDGE)
        self.size_c.configure(selectbackground="#c4c4c4")
        self.size_c.configure(selectforeground="black")
        self.size_c.configure(width=883)

        self.shape_c = Canvas(self.size_c)
        self.shape_c.place(relx=0.045, rely=0.055, relheight=0.876
                , relwidth=0.921)
        self.shape_c.configure(background="#d9d9d9")
        self.shape_c.configure(borderwidth="2")
        self.shape_c.configure(highlightbackground="#d9d9d9")
        self.shape_c.configure(highlightcolor="black")
        self.shape_c.configure(insertbackground="black")
        self.shape_c.configure(relief=RIDGE)
        self.shape_c.configure(selectbackground="#c4c4c4")
        self.shape_c.configure(selectforeground="black")
        self.shape_c.configure(width=813)






if __name__ == '__main__':
    vp_start_gui()



