#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Nov 04, 2018 06:41:07 PM +0200  platform: Windows NT

import sys
from Right_Triangle import *
from Isosceles_tri import *
from Square import *
from Equilateral_Triangle import *
from Rectangle import *
from Parallelogram import *
from Circle import *
from Ellipse import *
import hide

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def calc_shape(txt, shape, data):
    global was_hidden
    if not was_hidden:
        obj = data.get_obj(shape)
        if type(obj[0]) is not Polygon:
            area = str(obj[0].calc_area()) + " pixel^2"
        else:
            area = str(obj[0].calc_area())
        txt.configure(text=area)
        print('Shape_Func_support.calc_shape')
        sys.stdout.flush()
    else:
        destroy_window()

def delete_shape(canvas, shape, data):
    global was_hidden
    if not was_hidden:
        canvas.delete(shape)
        data.delete_value(shape)
        destroy_window()
        print('Shape_Func_support.delete_shape')
        sys.stdout.flush()
    else:
        destroy_window()


def hide_shape(root, canvas, shape, data):
    global was_hidden
    if not was_hidden:
        canvas.delete(shape)
        hide.create_New_Toplevel(root, canvas, shape, data)
        print('Shape_Func_support.hide_shape')
        was_hidden = True
        sys.stdout.flush()
    else:
        destroy_window()

def move_shape(canvas, shape, data):
    global was_hidden
    if not was_hidden:
        global is_move
        is_move = True
        pass
    else:
        destroy_window()



def init(top, gui, *args, **kwargs):
    global is_move, was_hidden
    global w, top_level, root
    was_hidden = False
    is_move = False
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Shape_Func
    Shape_Func.vp_start_gui()


